import Head from 'next/head'
import Link from 'next/link'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import NavigationBar from '../components/NavigationBar'
import 'bootstrap/dist/css/bootstrap.min.css';
import { Container, Navbar, Nav } from 'react-bootstrap';
import HomePage from './HomePage'

export default function Home() {

    return (
        <div>
            <Head>
                <title>PlantWorks</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="apple-touch-icon" sizes="180x180" href="/favicon_io/apple-touch-icon.png" />
                <link rel="icon" type="image/png" sizes="32x32" href="/favicon_io/favicon-32x32.png" />
                <link rel="manifest" href="/favicon_io/site.webmanifest" />
            </Head>
                <div>
                    <NavigationBar />
                    <HomePage />
                </div>
        </div>
    )
}
